// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh03B-GZa4vKySYEOQmaKlChNiL5pq56g',
    appId: '1:461905826629:web:01c8d4a4c5e40c97c9e42c',
    messagingSenderId: '461905826629',
    projectId: 'uas-pbb-95513',
    authDomain: 'uas-pbb-95513.firebaseapp.com',
    storageBucket: 'uas-pbb-95513.firebasestorage.app',
    measurementId: 'G-WTC6KZZ8Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfRiPGnQR0jTSPUhqB8zONFGUO0WurkOE',
    appId: '1:461905826629:android:96ce0536b303b106c9e42c',
    messagingSenderId: '461905826629',
    projectId: 'uas-pbb-95513',
    storageBucket: 'uas-pbb-95513.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8tlur6LzeKYHrRldylhc45FP9RaaHwMQ',
    appId: '1:461905826629:ios:ea7a8cae01d20689c9e42c',
    messagingSenderId: '461905826629',
    projectId: 'uas-pbb-95513',
    storageBucket: 'uas-pbb-95513.firebasestorage.app',
    iosBundleId: 'com.example.uasPbb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8tlur6LzeKYHrRldylhc45FP9RaaHwMQ',
    appId: '1:461905826629:ios:ea7a8cae01d20689c9e42c',
    messagingSenderId: '461905826629',
    projectId: 'uas-pbb-95513',
    storageBucket: 'uas-pbb-95513.firebasestorage.app',
    iosBundleId: 'com.example.uasPbb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh03B-GZa4vKySYEOQmaKlChNiL5pq56g',
    appId: '1:461905826629:web:7f0923a5d72fe0cbc9e42c',
    messagingSenderId: '461905826629',
    projectId: 'uas-pbb-95513',
    authDomain: 'uas-pbb-95513.firebaseapp.com',
    storageBucket: 'uas-pbb-95513.firebasestorage.app',
    measurementId: 'G-9PTH1CLWN0',
  );
}
